# Generated by Django 2.2.3 on 2019-07-03 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='QA', max_length=200)),
                ('short_description', models.TextField(default='Lorem')),
                ('job_description', models.TextField(default='Lorem')),
                ('skills', models.TextField(default='Lorem')),
            ],
        ),
        migrations.CreateModel(
            name='Career_Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Lorem', max_length=200)),
                ('last_name', models.CharField(default='Lorem', max_length=200)),
                ('phone', models.CharField(default='98000000', max_length=500)),
                ('cv', models.FileField(upload_to='careers/static/careers/site-data/career-apply')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.Career')),
            ],
        ),
    ]
