# Generated by Django 2.2.3 on 2019-07-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='John', max_length=200)),
                ('designation', models.CharField(default='Software Engineer', max_length=200)),
                ('image', models.ImageField(upload_to='team/static/team/site-data/team')),
            ],
        ),
    ]
