# Generated by Django 2.2.3 on 2019-07-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Portfolio/static/Portfolio/site-data/')),
                ('link', models.CharField(default='https://www.example.com', max_length=300)),
            ],
        ),
    ]
